lizard_task/urls.py
# (c) Nelen & Schuurmans.  GPL licensed, see LICENSE.txt.
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from lizard_ui.urls import debugmode_urlpatterns

from lizard_task.views import TasksView
from lizard_task.views import TaskDetailView
from lizard_task.views import TaskExecutionDetailView

admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^admin/', include(admin.site.urls)),
    url(r'^$',
        TasksView.as_view(),
        name='lizard_task_home'),
    url(r'^(?P<task_id>\d+)/$',
        TaskDetailView.as_view(),
        name='lizard_task_detail'),
    url(r'^execution/(?P<task_execution_id>\d+)/$',
        TaskExecutionDetailView.as_view(),
        name='lizard_task_execution_detail'),
    )
urlpatterns += debugmode_urlpatterns()

lizard_task/models.py
# (c) Nelen & Schuurmans.  GPL licensed, see LICENSE.txt.
# from django.db import models

import json

from celery.execute import send_task
from django.db import models
from django.core.urlresolvers import reverse

from lizard_security.models import DataSet
from lizard_security.manager import FilteredManager

from djcelery.models import PeriodicTask
from djcelery.models import TaskState


LOGGING_LEVELS = (
    (10, u'DEBUG'),
    (20, u'INFO'),
    (30, u'WARNING'),
    (40, u'ERROR'),
    (50, u'CRITICAL'),
)


class SecuredPeriodicTask(PeriodicTask):
    """
    Adds data_set to PeriodicTask to provide security.
    """
    objects = FilteredManager()
    data_set = models.ForeignKey(DataSet, null=True, blank=True)
    staff_only = models.BooleanField(default=True)

    class Meta:
        ordering = ('name', )

    def latest_state(self):
        """
        Fetch current associated task state.

        In order for this function to work, the task need a taskname
        provided.
        """
        try:
            task_uuid = TaskExecution.objects.filter(
                task=self).order_by('-dt_start')[0].task_uuid
            return TaskState.objects.get(task_id=task_uuid)
        except IndexError:
            return None

    def latest_taskexecution(self):
        return self.taskexecution_set.latest()

    def send_task(self, username=None):
        args_params = json.loads(self.args)
        kwargs_params = json.loads(self.kwargs)
        kwargs_params["username"] = username or '-'
        result = send_task(self.task, args=args_params, kwargs=kwargs_params)

    def get_absolute_url(self):
        return reverse('lizard_task_detail', kwargs={'task_id': self.id})


class TaskExecution(models.Model):
    """
    Keep track of executions of a SecuredPeriodicTask.
    """
    task = models.ForeignKey(SecuredPeriodicTask,
                             null=True, blank=True)
    task_uuid = models.CharField(max_length=255, unique=True)
    started_by = models.CharField(max_length=128, null=True, blank=True)
    dt_start = models.DateTimeField(auto_now_add=True)
    dt_finish = models.DateTimeField(null=True,
                                     blank=True)
    result = models.CharField(max_length=80, null=True, blank=True)
    #supports_object_permissions = True
    objects = FilteredManager()
    data_set = models.ForeignKey(DataSet, null=True, blank=True,
                                 related_name="taskexecution_data_set")

    class Meta:
        get_latest_by = "dt_start"
        ordering = ("-dt_start", )

    def __unicode__(self):
        return "%s %s" % (self.task or '-', self.id)

    def task_state(self):
        return TaskState.objects.get(task_id=self.task_uuid)

    def get_absolute_url(self):
        return reverse('lizard_task_execution_detail', kwargs={
                'task_execution_id': self.id})

    def delta_time(self):
        if self.dt_start and self.dt_finish:
            return self.dt_finish - self.dt_start
        else:
            return None


class TaskLogging(models.Model):
    """
    Gets filled by the DBLoggingHandler
    """
    task_execution = models.ForeignKey(TaskExecution)
    time = models.DateTimeField(blank=True, null=True)
    level = models.IntegerField(
        choices=LOGGING_LEVELS,
        blank=True,
        null=True)
    message = models.CharField(max_length=256)
    supports_object_permissions = True
    objects = FilteredManager()
    data_set = models.ForeignKey(DataSet, null=True, blank=True)

    class Meta:
        get_latest_by = "time"
        ordering = ('time', )

    def __unicode__(self):
        return '%s: %s' % (str(self.time), self.message)

lizard_task/views.py
"""
API views not coupled to models.
"""
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect

from lizard_task.models import SecuredPeriodicTask
from lizard_task.models import TaskExecution
from lizard_map.views import AppView


def member_functioneelbeheerder_group(user):
    """Return true is the user is a member of
    functioneelbeheerder usergroup.
    @TODO place this function central,
    it is a copy from lizard_portal.view"""
    functioneelbeheerder_groups = user.user_group_memberships.filter(
	name__contains='functioneel beheerder')
    if functioneelbeheerder_groups.exists():
	return True
    return False


class SendTask(object):
    """
    Inherit this class in your view to react on post task messages.
    """
    def post(self, request, *args, **kwargs):
        """
        Start SecuredPeriodicTask with pk task_pk.
        """
        pk = request.POST['task_pk']
        user = self.request.user
        # Lizard security is at work here.
        try:
            periodic_task = SecuredPeriodicTask.objects.get(pk=pk)
        except SecuredPeriodicTask.DoesNotExist:
            msg = ("Taak '%s' kan niet gevonden worden of mag niet worden uitgevoerd" %
                   periodic_task.name)
            return HttpResponseRedirect('./?msg=%s' % msg)
        # Staff-only?
        if not user.is_staff and periodic_task.staff_only:
            msg = ("Taak '%s' mag alleen door staff worden uitgevoerd." %
                   periodic_task.name)
            return HttpResponseRedirect('./?msg=%s' % msg)

        if not (member_functioneelbeheerder_group(user) or user.is_superuser):
            msg = ("Taak '%s' mag alleen door functioneelbeheerder worden uitgevoerd." %
                   periodic_task.name)
            return HttpResponseRedirect('./?msg=%s' % msg)
	
        periodic_task.send_task(username=request.user.username)
        msg = "Taak '%s' is in de wachtrij geplaatst." % periodic_task.name
        return HttpResponseRedirect('./?msg=%s' % msg)

    def is_functioneelbeheerder(self):
        user = self.request.user
        return member_functioneelbeheerder_group(user)

    def is_superuser(self):
        return self.request.user.is_superuser


class TasksView(SendTask, AppView):
    """
    Show a list of all available tasks
    """

    template_name = "lizard_task/tasks_table_view.html"
    msg = ""

    def tasks(self):
        tasks = SecuredPeriodicTask.objects.all()
        if not self.request.user.is_staff:
            # Filter out non-staff tasks
            tasks = tasks.filter(staff_only=False)
        return tasks

    def get(self, request, *args, **kwargs):
        self.msg = request.GET.get('msg', '')
        return super(TasksView, self).get(request, *args, **kwargs)


class TaskDetailView(SendTask, AppView):
    """
    Show a task in detail, with history
    """

    template_name = 'lizard_task/task_detail.html'

    def task(self):
        return SecuredPeriodicTask.objects.get(pk=self.task_id)

    def get(self, request, *args, **kwargs):
        self.msg = request.GET.get('msg', '')
        self.task_id = kwargs['task_id']
        return super(TaskDetailView, self).get(request, *args, **kwargs)


class TaskExecutionDetailView(AppView):
    """
    Show a task execution with logs
    """

    template_name = 'lizard_task/task_execution_detail.html'

    def task_execution(self):
        return TaskExecution.objects.get(pk=self.task_execution_id)

    def task(self):
        task_execution = self.task_execution()
        return task_execution.task

    def get(self, request, *args, **kwargs):
        self.task_execution_id = kwargs['task_execution_id']
        return super(TaskExecutionDetailView, self).get(request, *args, **kwargs)

lizard_task/templates/lizard_task/task_detail.html
{% extends "admin/base_site.html" %}

{% block extrahead %}
  {% if view.msg %}
    <meta http-equiv="refresh" content="5; url=./" >
  {% else %}
    <meta http-equiv="refresh" content="10" >
  {% endif %}
{% endblock %}

{% block title %}
Serverproces: {{ view.task }}
{% endblock title %}

{% block branding %}
  <h1 id="site-name">Serverproces: {{ view.task }}</h1>
{% endblock branding %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url "lizard_task_home" %}">Overzicht serverprocessen</a>
</div>
{% endblock %}

{% block content %}

{% if view.msg %}
<h4>{{ view.msg }}</h4>
{% else %}
<h4>Klik op 'Start' om de taak op te staren.</h4>
{% endif %}

<form action="" method="POST">{% csrf_token %}
  <input type="hidden" name="task_pk" value="{{ view.task.pk }}" />
  {% if view.is_functioneelbeheerder or view.is_superuser %}
    <input type="submit" name="action"  value="start"/>
  {% else %}
    <input disabled type="submit" name="action" title="Voor functioneelbeheerder" value="start" />
  {% endif %}
</form>

<div class="module">
  <table width="100%">
    <thead>
      <tr>
        <th>
          UUID
        </th>
        <th>
          Opgestart door
        </th>
        <th>
          Start uitvoering
        </th>
        <th>
          Runtime (s)
        </th>
        <th>
          Uitvoerder
        </th>
        <th>
          Resultaat
        </th>
        <th>
          Status
        </th>
      </tr>
    </thead>
    <tbody>
    {% for task_execution in view.task.taskexecution_set.all %}
    <tr class="{% cycle 'row1' 'row2' %}">
      <td>
        <a href="{{ task_execution.get_absolute_url }}">{{ task_execution.task_uuid }}</a>
      </td>
      <td>
        {% firstof task_execution.started_by 'onbekend' %}
      </td>
      <td>
        {% firstof task_execution.dt_start 'onbekend' %}
      </td>
      <td>
        {% firstof task_execution.delta_time '-' %}
      </td>
      <td>
        {% firstof task_execution.task_state.worker 'onbekend' %}
      </td>
      <td>
        {% ifequal task_execution.result 'ok' %}
          <span style="color: green;">
        {% else %}
          {% ifequal task_execution.result 'failure' %}
            <span style="color: red;">
          {% else %}
            <span>
          {% endifequal %}
        {% endifequal %}
          <strong>
            {% firstof task_execution.task_state.result task_execution.result '-' %}
          </strong>
        </span>
      </td>
      <td>
        {% ifequal task_execution.task_state.state 'SUCCESS' %}
          <span style="color: green;">
        {% else %}
          {% ifequal task_execution.task_state.state 'FAILURE' %}
            <span style="color: red;">
          {% else %}
            {% ifequal task_execution.task_state.state 'STARTED' %}
              <span>
            {% else %}
              <span>
            {% endifequal %}
          {% endifequal %}
        {% endifequal %}
        <strong>{{ task_execution.task_state.state }}</strong>
        </span>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td>
        Geen runs beschikbaar.
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

lizard_task/templates/lizard_task/task_execution_detail.html
{% extends "admin/base_site.html" %}

{% block extrahead %}
{% ifequal view.task_execution.task_state.state 'STARTED' %}
<meta http-equiv="refresh" content="10" >
{% endifequal %}
{% endblock %}

{% block title %}
Serverproces uitvoer
{% endblock title %}

{% block branding %}
  <h1 id="site-name">Serverproces uitvoer</h1>
{% endblock branding %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url "lizard_task_home" %}">Overzicht serverprocessen</a>
  {% if view.task %}
  <a href="{{ view.task.get_absolute_url }}"> &rsaquo; {{ view.task }}</a>
  {% endif %}
</div>
{% endblock %}

{% block content %}
<h3>Taak uitvoer details</h3>

<div class="module">
  <table width="100%">
    <tr>
      <th>
        Taak
      </th>
      <td>
        {{ view.task_execution }}
      </td>
    </tr>
    <tr>
      <th>
        Resultaat
      </th>
      <td>
        {% ifequal view.task_execution.result 'ok' %}
          <span style="color: green;">
        {% else %}
          {% ifequal view.task_execution.result 'failure' %}
            <span style="color: red;">
          {% else %}
            <span>
          {% endifequal %}
        {% endifequal %}
          <strong>
            {% firstof view.task_execution.task_state.result view.task_execution.result '-' %}
          </strong>
        </span>
      </td>
    </tr>
    <tr>
      <th>
        UUID
      </th>
      <td>
        {{ view.task_execution.task_uuid }}
      </td>
    </tr>
    <tr>
      <th>
        Status
      </th>
      <td>
        {% ifequal view.task_execution.task_state.state 'SUCCESS' %}
          <span style="color: green;">
        {% else %}
          {% ifequal view.task_execution.task_state.state 'FAILURE' %}
            <span style="color: red;">
          {% else %}
            {% ifequal view.task_execution.task_state.state 'STARTED' %}
              <span>
            {% else %}
              <span>
            {% endifequal %}
          {% endifequal %}
        {% endifequal %}
        <strong>{{ view.task_execution.task_state.state }}</strong>
        </span>
      </td>
    </tr>
    <tr>
      <th>
        Opgestart door
      </th>
      <td>
        {% firstof view.task_execution.started_by 'onbekend' %}
      </td>
    </tr>
    <tr>
      <th>
        Gestart
      </th>
      <td>
        {{ view.task_execution.dt_start }}
      </td>
    </tr>
    <tr>
      <th>
        Runtime
      </th>
      <td>
        {% firstof view.task_execution.delta_time '-' %}
      </td>
    </tr>
    <tr>
      <th>
        Ontvangen
      </th>
      <td>
        {{ view.task_execution.task_state.tstamp }}
      </td>
    </tr>
    <tr>
      <th>
        Uitvoerder
      </th>
      <td>
        {% firstof view.task_execution.task_state.worker 'onbekend' %}
      </td>
    </tr>
  </table>
</div>

<h3>logging</h3>
<ul>
{% for logging in view.task_execution.tasklogging_set.all %}
<li>{{ logging }}</li>
{% empty %}
<li>geen logging beschikbaar</li>
{% endfor %}
</ul>

{% ifequal view.task_execution.task_state.state 'STARTED' %}
De taak is nog bezig, er volgen mogelijk nieuwe logregels.
{% endifequal %}

{% endblock content %}

lizard_task/templates/lizard_task/tasks_table_view.html
{% extends "admin/base_site.html" %}

{% block extrahead %}
  {% if view.msg %}
    <meta http-equiv="refresh" content="5; url=./" >
  {% else %}
    <meta http-equiv="refresh" content="10" >
  {% endif %}
{% endblock %}

{% block title %}Serverprocessen{% endblock %}

{% block branding %}
  <h1 id="site-name">Serverprocessen</h1>
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block content %}

  {% if view.msg %}
    <h4>{{ view.msg }}</h4>
  {% else %}
    <h4>Klik op 'Start' om een taak op te staren.</h4>
  {% endif %}

  <div class="module">
    <table width="100%">
      <thead>
        <th></th>
        <th>Taaknaam</th>
        <th>Aantal uitvoeringen</th>
	<th>Laatst opgestart door</th>
        <th>Laatste uitvoering</th>
        <th>Runtime (s)</th>
	<th>Crontab</th>
        <th>Laatste resultaat</th>
        <th>Status</th>
      </thead>
      <tbody>
      {% for task in view.tasks %}
        <tr class="{% cycle 'row1' 'row2' %}">
          <td>
            <form action="" method="POST">{% csrf_token %}
              <input type="hidden" name="task_pk" value="{{ task.pk }}" />
	      {% if view.is_functioneelbeheerder or view.is_superuser %}
                <input type="submit" name="action"  value="start" />
	      {% else %}
		<input disabled type="submit" name="action" title="Voor functioneelbeheerder" value="start" />
              {% endif %}
            </form>
          </td>
          <td><a href="{{ task.get_absolute_url }}">{{ task.name }}</a></td>
          <td>
            {{ task.taskexecution_set.all.count }}
          </td>
	  <td>
            {% firstof task.taskexecution_set.latest.started_by 'onbekend' %}
          </td>
          <td>{% firstof task.taskexecution_set.latest.dt_start '-' %}</td>
          <td>{% firstof task.taskexecution_set.latest.delta_time '-' %}</td>
	  <td><strong>{{ task.crontab }}</strong></td>
          <td>
              {% ifequal task.taskexecution_set.latest.result 'ok' %}
                <span style="color: green;">
              {% else %}
                {% ifequal task.taskexecution_set.latest.result 'failure' %}
                  <span style="color: red;">
                {% else %}
                  <span>
                {% endifequal %}
              {% endifequal %}
              <strong>
                {% firstof task.latest_state.result task.taskexecution_set.latest.result '-' %}
              </strong>
            </span>
          </td>
          <td>
            {% ifequal task.latest_state.state 'SUCCESS' %}
              <span style="color: green;">
            {% else %}
              {% ifequal task.latest_state.state 'FAILURE' %}
                <span style="color: red;">
              {% else %}
                {% ifequal task.latest_state.state 'STARTED' %}
                  <span>
                {% else %}
                  <span>
                {% endifequal %}
              {% endifequal %}
            {% endifequal %}
            <strong>{{ task.latest_state.state }}</strong>
            </span>
          </td>
         </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}